import { getDatabase } from '@netlify/database';
import { randomUUID } from 'node:crypto';

export async function ensureDrinkLedger({eventId,ticketId,userId,creditsPurchased}){
  const db=getDatabase();const credits=Number(creditsPurchased);if(!eventId||!ticketId||!userId||!Number.isInteger(credits)||credits<1)throw new Error('Invalid drink ledger identity.');
  await db.sql`INSERT INTO wildones_drink_ledgers (event_id,ticket_id,user_id,credits_purchased,credits_redeemed,credits_remaining) VALUES (${eventId},${ticketId},${userId},${credits},0,${credits}) ON CONFLICT (event_id,ticket_id) DO NOTHING`;
  const rows=await db.sql`SELECT * FROM wildones_drink_ledgers WHERE event_id=${eventId} AND ticket_id=${ticketId}`;const row=rows[0];if(!row||row.user_id!==userId||Number(row.credits_purchased)!==credits)throw new Error('Drink ledger conflicts with entitlement.');return normalize(row);
}
export async function getDrinkLedger(eventId,ticketId){const rows=await getDatabase().sql`SELECT * FROM wildones_drink_ledgers WHERE event_id=${eventId} AND ticket_id=${ticketId}`;return rows[0]?normalize(rows[0]):null;}
export async function activateDrinkWristband({eventId,ticketId,userId,creditsPurchased,wristbandCode}){const code=String(wristbandCode||'').trim().slice(0,40);if(!code)throw new Error('Wristband identifier is required.');await ensureDrinkLedger({eventId,ticketId,userId,creditsPurchased});const db=getDatabase();const rows=await db.sql`UPDATE wildones_drink_ledgers SET wristband_code=COALESCE(wristband_code,${code}),wristband_activated_at=COALESCE(wristband_activated_at,NOW()),updated_at=NOW() WHERE event_id=${eventId} AND ticket_id=${ticketId} AND user_id=${userId} AND (wristband_code IS NULL OR wristband_code=${code}) RETURNING *`;if(!rows[0])throw new Error('This drink package is already linked to a different wristband.');return normalize(rows[0]);}
export async function redeemDrinkCredit({eventId,ticketId,userId,creditsPurchased}){await ensureDrinkLedger({eventId,ticketId,userId,creditsPurchased});const db=getDatabase(),client=await db.pool.connect();try{await client.query('BEGIN');const locked=await client.query('SELECT * FROM wildones_drink_ledgers WHERE event_id=$1 AND ticket_id=$2 AND user_id=$3 FOR UPDATE',[eventId,ticketId,userId]);const row=locked.rows[0];if(!row)throw new Error('Drink ledger not found.');if(!row.wristband_activated_at||!row.wristband_code){const e=new Error('Activate the guest wristband before redeeming credits.');e.code='WRISTBAND_REQUIRED';throw e;}if(Number(row.credits_remaining)<=0){const e=new Error('No drink credits remain.');e.code='NO_CREDITS';throw e;}const redemptionNumber=Number(row.credits_redeemed)+1,redemptionId=`dr_${randomUUID()}`;await client.query('INSERT INTO wildones_drink_redemptions (redemption_id,event_id,ticket_id,user_id,redemption_number,wristband_code) VALUES ($1,$2,$3,$4,$5,$6)',[redemptionId,eventId,ticketId,userId,redemptionNumber,row.wristband_code]);const updated=await client.query('UPDATE wildones_drink_ledgers SET credits_redeemed=credits_redeemed+1,credits_remaining=credits_remaining-1,updated_at=NOW() WHERE event_id=$1 AND ticket_id=$2 AND user_id=$3 RETURNING *',[eventId,ticketId,userId]);await client.query('COMMIT');return{ledger:normalize(updated.rows[0]),redemptionId,redemptionNumber};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
export async function listDrinkLedgers(eventId){const rows=await getDatabase().sql`SELECT * FROM wildones_drink_ledgers WHERE event_id=${eventId} ORDER BY updated_at DESC`;return rows.map(normalize);}
function normalize(row){return{eventId:row.event_id,ticketId:row.ticket_id,userId:row.user_id,creditsPurchased:Number(row.credits_purchased),creditsRedeemed:Number(row.credits_redeemed),creditsRemaining:Number(row.credits_remaining),wristbandCode:row.wristband_code||null,wristbandActivatedAt:row.wristband_activated_at?new Date(row.wristband_activated_at).toISOString():null,updatedAt:row.updated_at?new Date(row.updated_at).toISOString():null};}
