import { barCookie,barKeyMatches,clearBarCookie,createBarSession,readBarSession } from './_bar-auth.mjs';
import { blobStore } from './_blob-store.mjs';
import { entitlementFor } from './_addon-payments.mjs';
import { resolveEvent,toPublicEvent } from './_events.mjs';
import { loadApplication,loadTicket } from './_payments.mjs';
import { clientIp,json,readBody } from './_response.mjs';
import { sameOrigin } from './_security.mjs';
import { verifyTicketToken } from './_ticket-token.mjs';
import { STORES,eventKey,sha256 } from './_stores.mjs';
import { writeAudit } from './_audit.mjs';

function tokenFrom(v=''){const raw=String(v||'').trim();if(!raw)return'';try{return new URL(raw).searchParams.get('token')||raw;}catch{return raw;}}
async function loginRate(req){const store=blobStore(STORES.rateLimits),key=`bar-login/ip/${sha256(clientIp(req))}`,now=Date.now(),s=await store.get(key,{type:'json'}).catch(()=>null);return{store,key,state:s&&Number(s.windowStart)>now-900000?s:{windowStart:now,failures:0}};}
async function packageState(parsed){const ticket=await loadTicket(parsed.eventId,parsed.ticketId);if(!ticket||ticket.userId!==parsed.userId||ticket.status!=='checked_in')return{error:'Ticket must be checked in before bar package use.',status:403};const entitlement=await entitlementFor(parsed.eventId,parsed.ticketId,'drink_package');if(!entitlement||entitlement.status!=='active')return{error:'No active drink package is attached to this ticket.',status:404};const app=await loadApplication(parsed.eventId,ticket.applicationId);return{ticket,entitlement,guestName:app?.preferredName||app?.fullName||'Wild Ones Guest'};}

export default async(req)=>{
  if(req.method==='GET'){const session=readBarSession(req);return session?json({authenticated:true,event:toPublicEvent(resolveEvent({eventId:session.eventId}))}):json({authenticated:false},401);}
  if(req.method!=='POST')return json({error:'Method not allowed.'},405);if(!sameOrigin(req))return json({error:'Origin not allowed.'},403);let body;try{body=await readBody(req);}catch{return json({error:'Invalid request.'},400);}const action=String(body.action||'lookup');
  if(action==='logout')return json({ok:true},200,{'Set-Cookie':clearBarCookie()});
  if(action==='login'){const event=resolveEvent({eventId:body.eventId,slug:body.event});if(!event)return json({error:'Unknown event.'},400);let rate;try{rate=await loginRate(req);}catch{return json({error:'Bar login unavailable.'},503);}if(Number(rate.state.failures)>=10)return json({error:'Too many failed bar login attempts.'},429,{'Retry-After':'900'});if(!barKeyMatches(body.password||'')){await rate.store.setJSON(rate.key,{windowStart:rate.state.windowStart,failures:Number(rate.state.failures)+1,updatedAt:new Date().toISOString()}).catch(()=>{});return json({error:'Invalid bar password.'},401);}await rate.store.delete(rate.key).catch(()=>{});return json({ok:true,event:toPublicEvent(event)},200,{'Set-Cookie':barCookie(createBarSession(event.eventId))});}
  const session=readBarSession(req);if(!session)return json({error:'Unauthorized.'},401);const token=tokenFrom(body.token||body.value),parsed=verifyTicketToken(token);if(!parsed)return json({error:'Invalid ticket.',result:'invalid'},400);if(parsed.eventId!==session.eventId)return json({error:'Ticket is for a different event.',result:'wrong_event'},403);const state=await packageState(parsed);if(state.error)return json({error:state.error,result:'unavailable'},state.status);const {ticket,entitlement,guestName}=state;
  if(action==='lookup')return json({ok:true,eventId:parsed.eventId,ticketId:ticket.ticketId,guestName,package:{status:entitlement.status,creditsPurchased:entitlement.creditsPurchased,creditsRedeemed:entitlement.creditsRedeemed,creditsRemaining:entitlement.creditsRemaining,wristbandActivatedAt:entitlement.wristbandActivatedAt,wristbandCode:entitlement.wristbandCode||null}});
  const store=blobStore(STORES.entitlements),key=eventKey(parsed.eventId,`${parsed.ticketId}/drink_package`),now=new Date().toISOString();
  if(action==='activate'){if(entitlement.wristbandActivatedAt)return json({ok:true,alreadyActivated:true,guestName,package:entitlement});const wristbandCode=String(body.wristbandCode||'').trim().slice(0,40);if(!wristbandCode)return json({error:'Enter or scan the wristband identifier.'},400);const updated={...entitlement,wristbandCode,wristbandActivatedAt:now,activatedBySession:session.nonce,updatedAt:now};await store.setJSON(key,updated);await writeAudit({eventId:parsed.eventId,action:'drink_package.activated',actor:'bar',targetType:'ticket',targetId:parsed.ticketId,detail:{wristbandCode}});return json({ok:true,guestName,package:updated});}
  if(action==='redeem'){if(!entitlement.wristbandActivatedAt)return json({error:'Activate the guest wristband before redeeming credits.'},409);if(Number(entitlement.creditsRemaining||0)<=0)return json({error:'No drink credits remain.',result:'empty'},409);const redemptionNumber=Number(entitlement.creditsRedeemed||0)+1,redemptionId=`${parsed.ticketId}-credit-${redemptionNumber}`,redemption={redemptionId,eventId:parsed.eventId,ticketId:parsed.ticketId,userId:parsed.userId,redeemedAt:now,redeemedBySession:session.nonce,wristbandCode:entitlement.wristbandCode||null};await blobStore(STORES.redemptions).setJSON(eventKey(parsed.eventId,redemptionId),redemption);const updated={...entitlement,creditsRedeemed:redemptionNumber,creditsRemaining:Math.max(0,Number(entitlement.creditsPurchased||0)-redemptionNumber),lastRedeemedAt:now,updatedAt:now};await store.setJSON(key,updated);const latest=await entitlementFor(parsed.eventId,parsed.ticketId,'drink_package');if(Number(latest?.creditsRedeemed||0)<redemptionNumber)return json({error:'Redemption state changed. Re-scan before serving.',result:'conflict'},409);await writeAudit({eventId:parsed.eventId,action:'drink_package.credit_redeemed',actor:'bar',targetType:'ticket',targetId:parsed.ticketId,detail:{redemptionNumber,creditsRemaining:updated.creditsRemaining}});return json({ok:true,result:'redeemed',guestName,redemptionNumber,creditsRemaining:updated.creditsRemaining});}
  return json({error:'Unknown bar action.'},400);
};
export const config={path:'/api/bar'};
