import { blobStore } from './_blob-store.mjs';
import { listEvents,toPublicEvent } from './_events.mjs';
import { clearPassportCookie,readPassportSession } from './_passport-auth.mjs';
import { json } from './_response.mjs';
import { STORES } from './_stores.mjs';

async function userRecords(storeName,eventId,userId){const store=blobStore(storeName),listed=await store.list({prefix:`${eventId}/`}),out=[];for(const {key} of listed.blobs||[]){const value=await store.get(key,{type:'json'}).catch(()=>null);if(value?.eventId===eventId&&value?.userId===userId)out.push(value);}return out;}
export default async(req)=>{const session=readPassportSession(req);if(req.method==='DELETE')return json({ok:true},200,{'Set-Cookie':clearPassportCookie()});if(req.method!=='GET')return json({error:'Method not allowed.'},405);if(!session)return json({authenticated:false},401);const user=await blobStore(STORES.users).get(session.userId,{type:'json'}).catch(()=>null);if(!user||user.status!=='active'||user.email!==session.email)return json({authenticated:false},401);const realms=[];for(const event of listEvents({includeHidden:true})){const [applications,tickets,entitlements,waivers,checkins]=await Promise.all([userRecords(STORES.applications,event.eventId,user.userId),userRecords(STORES.tickets,event.eventId,user.userId),userRecords(STORES.entitlements,event.eventId,user.userId),userRecords(STORES.waivers,event.eventId,user.userId),userRecords(STORES.checkins,event.eventId,user.userId)]);const ticket=tickets.sort((a,b)=>String(b.issuedAt||'').localeCompare(String(a.issuedAt||'')))[0]||null;realms.push({event:toPublicEvent(event),application:applications[0]||null,ticket:ticket?{ticketId:ticket.ticketId,status:ticket.status,issuedAt:ticket.issuedAt,checkedInAt:ticket.checkedInAt,waiverSignedAt:ticket.waiverSignedAt}:null,entitlements:entitlements.map(x=>({addonType:x.addonType,status:x.status,purchasedAt:x.purchasedAt,creditsPurchased:x.creditsPurchased??null,creditsRedeemed:x.creditsRedeemed??null,creditsRemaining:x.creditsRemaining??null,departureTime:x.departureTime??null})),waiverSigned:Boolean(waivers.length),checkedIn:Boolean(checkins.length)});}const completed=realms.filter(r=>r.checkedIn).length;return json({authenticated:true,user:{userId:user.userId,email:user.email,fullName:user.fullName,preferredName:user.preferredName},cycle:{cycleId:realms[0]?.event?.cycleId||null,completed,total:realms.length,complete:completed===realms.length},realms});};
export const config={path:'/api/passport'};
