import { consumeMagicLink,createPassportSession,passportCookie } from './_passport-auth.mjs';
import { blobStore } from './_blob-store.mjs';
import { sameOrigin } from './_security.mjs';
import { STORES,userKey } from './_stores.mjs';

function esc(value=''){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function page(content,status=200){return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#030407"><title>Wild Ones Passport · ENTER WILD ONES</title><link rel="stylesheet" href="/assets/css/transactional-hero.css"></head><body class="tx-generated-page"><header class="topbar"><a class="tx-brand" href="/">ENTER WILD ONES</a><nav class="tx-nav" aria-label="Main navigation"><a href="/#realms">THE REALMS</a><a href="/passport">PASSPORT</a></nav></header><main class="tx-generated-shell"><section class="tx-generated-card"><p class="eyebrow">ENTER WILD ONES · SECURE PASSPORT</p>${content}</section></main><footer class="site-footer"><nav aria-label="Footer navigation"><a href="/#realms">THE REALMS</a><a href="/passport">PASSPORT</a><a href="mailto:help@enterwildones.com">CONTACT</a></nav><span>WILD ONES LLC / HAWAI'I / ENTERWILDONES.COM</span></footer></body></html>`,{status,headers:{'Cache-Control':'no-store, no-cache, must-revalidate','Content-Type':'text/html; charset=utf-8','Referrer-Policy':'no-referrer','X-Robots-Tag':'noindex, nofollow, noarchive'}});}
function message(text,status=200){return page(`<h1 class="tx-cycle-title">${esc(text)}</h1><p>Your secure Wild Ones Passport session could not continue from this link. Return to Passport to request a new sign-in link if needed.</p><div class="tx-actions"><a class="button" href="/passport">Return to Passport</a></div>`,status);}
function confirmPage(token){return page(`<h1 class="tx-cycle-title">Open Your Wild Ones Passport</h1><p>For your security, confirm that you want to use this one-time sign-in link. This link is not consumed until you continue.</p><form method="post" action="/passport/verify"><input type="hidden" name="token" value="${esc(token)}"><button type="submit">Continue to Passport</button></form><p class="tx-generated-note">This link expires 15 minutes after it was requested and can be used only once.</p>`);}
export default async(req)=>{if(req.method==='GET'){const token=new URL(req.url).searchParams.get('token')||'';if(!token)return message('This Passport sign-in link is invalid.',400);return confirmPage(token);}if(req.method!=='POST')return message('Method not allowed.',405);if(!sameOrigin(req))return message('Origin not allowed.',403);let token='';try{const form=await req.formData();token=String(form.get('token')||'');}catch{return message('This Passport sign-in request is invalid.',400);}try{const data=await consumeMagicLink(token);if(!data)return message('This Passport sign-in link is invalid, expired, or already used.',400);const user=await blobStore(STORES.users).get(userKey(data.userId),{type:'json'}).catch(()=>null);if(!user||user.status!=='active'||user.email!==data.email)return message('Passport identity could not be verified.',403);const session=createPassportSession(user);return new Response(null,{status:303,headers:{Location:'/passport','Set-Cookie':passportCookie(session),'Cache-Control':'no-store'}});}catch(error){console.error('Passport verification failed',error);return message('Passport sign-in is temporarily unavailable.',503);}};
export const config={path:'/passport/verify'};
