import { consumeMagicLink,createPassportSession,passportCookie } from './_passport-auth.mjs';
import { blobStore } from './_blob-store.mjs';
import { sameOrigin } from './_security.mjs';
import { STORES,userKey } from './_stores.mjs';

function esc(value=''){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function page(content,status=200){return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Wild Ones Passport</title></head><body style="margin:0;background:#050505;color:#f6f1e8;font-family:system-ui;display:grid;min-height:100vh;place-items:center"><main style="width:min(620px,calc(100% - 40px));padding:40px 20px;text-align:center"><p style="letter-spacing:.25em;font-size:11px">ENTER WILD ONES</p>${content}</main></body></html>`,{status,headers:{'Cache-Control':'no-store, no-cache, must-revalidate','Content-Type':'text/html; charset=utf-8','Referrer-Policy':'no-referrer','X-Robots-Tag':'noindex, nofollow'}});}
function message(text,status=200){return page(`<h1>${esc(text)}</h1>`,status);}
function confirmPage(token){return page(`<h1 style="font-size:clamp(34px,7vw,54px);line-height:1.05;margin:20px 0">Open Your Wild Ones Passport</h1><p style="color:#aaa;line-height:1.7;margin:0 auto 26px;max-width:500px">For your security, confirm that you want to use this one-time sign-in link. The link is not consumed until you continue.</p><form method="post" action="/passport/verify"><input type="hidden" name="token" value="${esc(token)}"><button type="submit" style="appearance:none;border:1px solid #f1ece2;background:#f1ece2;color:#070708;padding:16px 24px;font:900 12px system-ui;letter-spacing:.16em;text-transform:uppercase;cursor:pointer">Continue to Passport</button></form><p style="margin-top:22px;color:#777;font-size:12px">This link expires 15 minutes after it was requested and can be used only once.</p>`);}
export default async(req)=>{if(req.method==='GET'){const token=new URL(req.url).searchParams.get('token')||'';if(!token)return message('This Passport sign-in link is invalid.',400);return confirmPage(token);}if(req.method!=='POST')return message('Method not allowed.',405);if(!sameOrigin(req))return message('Origin not allowed.',403);let token='';try{const form=await req.formData();token=String(form.get('token')||'');}catch{return message('This Passport sign-in request is invalid.',400);}try{const data=await consumeMagicLink(token);if(!data)return message('This Passport sign-in link is invalid, expired, or already used.',400);const user=await blobStore(STORES.users).get(userKey(data.userId),{type:'json'}).catch(()=>null);if(!user||user.status!=='active'||user.email!==data.email)return message('Passport identity could not be verified.',403);const session=createPassportSession(user);return new Response(null,{status:303,headers:{Location:'/passport','Set-Cookie':passportCookie(session),'Cache-Control':'no-store'}});}catch(error){console.error('Passport verification failed',error);return message('Passport sign-in is temporarily unavailable.',503);}};
export const config={path:'/passport/verify'};
