import { blobStore } from './_blob-store.mjs';
import { randomUUID } from 'node:crypto';
import { finalizePaidSession, markPaymentInactiveByIntent, notePartialRefundByIntent, restorePaymentByIntent } from './_payments.mjs';
import { verifyStripeSignature } from './_stripe.mjs';
import { getEvent } from './_events.mjs';
import { STORES, eventKey } from './_stores.mjs';

async function claim(event){const store=blobStore(STORES.stripeEvents);const key=String(event.id||'');if(!/^evt_[A-Za-z0-9_]+$/.test(key))throw new Error('Invalid Stripe event ID.');const existing=await store.get(key,{type:'json'}).catch(()=>null);if(existing?.status==='processed')return{duplicate:true};const nonce=randomUUID();const now=new Date().toISOString();await store.setJSON(key,{stripeEventId:key,type:event.type,status:'processing',nonce,startedAt:now,updatedAt:now});const latest=await store.get(key,{type:'json'}).catch(()=>null);return latest?.nonce===nonce?{duplicate:false,store,key,nonce,type:event.type}:{duplicate:true};}
async function complete(c,status,error=null){if(!c?.store)return;await c.store.setJSON(c.key,{stripeEventId:c.key,status,type:c.type||null,nonce:c.nonce,completedAt:new Date().toISOString(),error:error?String(error).slice(0,500):null,updatedAt:new Date().toISOString()});}
async function markExpired(session){const eventId=String(session.metadata?.event_id||'');if(!getEvent(eventId)||!session.id)return;const store=blobStore(STORES.payments);const key=eventKey(eventId,session.id);const existing=await store.get(key,{type:'json'}).catch(()=>null);if(existing?.status==='paid')return;await store.setJSON(key,{...(existing||{}),paymentId:session.id,eventId,status:'expired',updatedAt:new Date().toISOString()});}
export default async(req)=>{if(req.method!=='POST')return new Response('Method not allowed.',{status:405});const raw=await req.text();if(!verifyStripeSignature(raw,req.headers.get('stripe-signature')))return new Response('Invalid signature.',{status:400});let event;try{event=JSON.parse(raw);}catch{return new Response('Invalid payload.',{status:400});}let c;try{c=await claim(event);if(c.duplicate)return new Response('ok',{status:200});const obj=event.data?.object||{};switch(event.type){case'checkout.session.completed':case'checkout.session.async_payment_succeeded':if(obj.payment_status==='paid')await finalizePaidSession(obj,{source:'webhook'});break;case'checkout.session.expired':await markExpired(obj);break;case'charge.refunded':if(obj.payment_intent){const full=Boolean(obj.refunded)||Number(obj.amount_refunded||0)>=Number(obj.amount||0);if(full)await markPaymentInactiveByIntent(obj.payment_intent,'refunded',{chargeId:obj.id,amountRefunded:Number(obj.amount_refunded||0),chargeAmount:Number(obj.amount||0)});else await notePartialRefundByIntent(obj.payment_intent,{chargeId:obj.id,amountRefunded:Number(obj.amount_refunded||0),chargeAmount:Number(obj.amount||0)});}break;case'charge.dispute.created':if(obj.payment_intent)await markPaymentInactiveByIntent(obj.payment_intent,'disputed',{disputeId:obj.id,chargeId:obj.charge||null});break;case'charge.dispute.closed':{const pi=String(obj.payment_intent||'');if(pi&&obj.status==='won')await restorePaymentByIntent(pi,{disputeId:obj.id});break;}default:break;}await complete(c,'processed');return new Response('ok',{status:200});}catch(error){await complete(c,'failed',error).catch(()=>{});console.error('Wild Ones Stripe webhook failed:',error);return new Response('Webhook processing failed.',{status:500});}};
export const config={path:'/api/stripe/webhook'};
