import { blobStore } from './_blob-store.mjs';
import { verifyTicketToken } from './_ticket-token.mjs';
import { loadApplication, loadTicket } from './_payments.mjs';
import { json, clientIp, readBody } from './_response.mjs';
import { sameOrigin } from './_security.mjs';
import { STORES, eventKey, sha256 } from './_stores.mjs';
import { WAIVER_VERSION, waiverHash, waiverIsCurrent, waiverText } from './_waiver.mjs';
import { writeAudit } from './_audit.mjs';
function normalizeName(v=''){return String(v).trim().toLowerCase().replace(/\s+/g,' ');}
function active(ticket){return ticket&&['paid','checked_in'].includes(ticket.status);}
export default async(req)=>{const url=new URL(req.url);let body={};if(req.method==='POST'){if(!sameOrigin(req))return json({error:'Origin not allowed.'},403);try{body=await readBody(req);}catch{return json({error:'Invalid waiver request.'},400);}}else if(req.method!=='GET')return json({error:'Method not allowed.'},405);const token=String(body.token||url.searchParams.get('token')||'').trim();const parsed=verifyTicketToken(token);if(!parsed)return json({error:'Invalid ticket.'},400);const ticket=await loadTicket(parsed.eventId,parsed.ticketId);if(!active(ticket)||ticket.userId!==parsed.userId)return json({error:'This ticket is inactive.'},403);const waivers=blobStore(STORES.waivers);const existing=await waivers.get(eventKey(parsed.eventId,parsed.ticketId),{type:'json'}).catch(()=>null);if(req.method==='GET')return json({eventId:parsed.eventId,ticketId:parsed.ticketId,waiverVersion:WAIVER_VERSION,waiverText:waiverText(parsed.eventId),signed:waiverIsCurrent(existing,parsed.eventId),signedAt:existing?.signedAt||null});const application=await loadApplication(parsed.eventId,ticket.applicationId);const signerName=String(body.signerName||'').trim().slice(0,120);if(!signerName)return json({error:'Full legal name is required.'},400);if(application?.fullName&&normalizeName(signerName)!==normalizeName(application.fullName))return json({error:'The signature name must match the registered ticket holder.'},400);if(!(body.accept===true||String(body.accept).toLowerCase()==='yes'))return json({error:'You must affirmatively accept the waiver.'},400);const signedAt=new Date().toISOString();const record={waiverId:`waiver_${parsed.ticketId}`,eventId:parsed.eventId,ticketId:parsed.ticketId,userId:ticket.userId,applicationId:ticket.applicationId,waiverVersion:WAIVER_VERSION,waiverTextHash:waiverHash(parsed.eventId),signerName,signedAt,electronicConsent:true,userAgent:String(req.headers.get('user-agent')||'').slice(0,500),clientIpHash:sha256(clientIp(req))};await waivers.setJSON(eventKey(parsed.eventId,parsed.ticketId),record);const updated={...ticket,waiverSignedAt:signedAt,waiverVersion:record.waiverVersion,waiverTextHash:record.waiverTextHash,updatedAt:signedAt};await blobStore(STORES.tickets).setJSON(eventKey(parsed.eventId,parsed.ticketId),updated);await writeAudit({eventId:parsed.eventId,action:'waiver.signed',actor:'guest',targetType:'ticket',targetId:parsed.ticketId,detail:{waiverVersion:WAIVER_VERSION}});const accept=req.headers.get('accept')||'';if(accept.includes('text/html')||String(body.browser||'')==='1')return new Response(null,{status:303,headers:{Location:`/ticket?token=${encodeURIComponent(token)}`,'Cache-Control':'no-store'}});return json({ok:true,signed:true,signedAt,waiverVersion:WAIVER_VERSION});};
export const config={path:'/ticket/waiver'};
